name: Shared App Workflow

on:
  [push]

jobs:
  # Job for installing dependencies and linting code
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/app-setup
    - name: Lint
      run: npm run lint

